--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jojoe77777/FormAPI
build-by-default: true
branches:
- master
projects:
  FormAPI:
    path: ""
  libFormAPI:
    path: ""
    type: library
    model: virion
...
